GET http://localhost:3000/api/user/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaG93YXJkIiwiaWF0IjoxNjM3ODU4MTUzLCJleHAiOjE2Mzc4NTgyMTN9.Yh-FQMaY3DXjpFsCzNq3DU9-ZUG9bJA4MpxMeafPlK8
###

POST http://localhost:3000/api/user/account
Content-Type: application/json

{
    "email":"123@gmail.com",
    "pwd":"test12",
    "name":"Haowei"
}

###
POST http://localhost:3000/api/auth/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaG93YXJkIiwiaWF0IjoxNjM3ODU4MTUzfQ.wTh0J2tf_nnb0r0fpcHKCH4R1O55E4iYmwzt37qJbvg"
}

###
DELETE  http://localhost:3000/api/auth/logout

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaG93YXJkIiwiaWF0IjoxNjM3ODU4MTUzfQ.wTh0J2tf_nnb0r0fpcHKCH4R1O55E4iYmwzt37qJbvg"
}