#註冊
POST http://localhost:3000/api/user/account
Content-Type: application/json

{
	"email":"admin",
	"password":"admin",
	"name":"Menager"
}

###
GET http://localhost:3000/api/auth/valid
Content-Type: :application/json


###登入
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
	"email":"1@gmail.com",
	"password":"1"
}

###登出
DELETE  http://localhost:3000/api/auth/login
Content-Type: :application/json

