#註冊
POST http://localhost:3000/api/user/account
Content-Type: application/json

{
	"email":"testuser@gmail.com",
	"password":"ntut",
	"name":"測試使用"
}

###
GET http://localhost:3000/api/auth/valid
Content-Type: :application/json


###登入
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
	"email":"admin",
	"password":"admin"
}

###登出
DELETE  http://localhost:3000/api/auth/login
Content-Type: :application/json

