###
POST http://localhost:3000/api/activity/
Content-Type: application/json

{
  "subject":"中午訂餐",
  "store_id":1,
  "user_id":1,
  "createtime":"2021-12-20 14:38:12",
  "endtime":"2021-12-20 14:38:12"
}

###
GET http://localhost:3000/api/activity/
Content-Type: application/json

###
POST http://localhost:3000/api/activity/order
Content-Type: application/json

{
  "meals":
  [
    {
      "meal":"測試",
      "price":5,
      "num":10
    },
    {
      "meal":"測試2",
      "price":2,
      "num":3
    }
  ],
  "orderer":1,
  "activity":1
}