###
POST http://localhost:3000/api/store/
Content-Type: application/json

{
	"name":"八方雲集(台北忠孝東三店)",
	"phone":"(02)2731-5212",
	"address":"台北市大安區忠孝東路三段212號中華郵政限時大樓"
}

###
GET  http://localhost:3000/api/store/
Content-Type: application/json


###
GET  http://localhost:3000/api/store/1
Content-Type: application/json

###
POST http://localhost:3000/api/manager/meal/1
Content-Type: application/json

{
	"meals":
	[
		{
			"name":"玉米濃湯",
			"price":30,
			"note":"測試",
			"store_id":22
		},
		{
			"name":"玉米濃湯",
			"price":30,
			"note":"測試",
			"store_id":22
		}
	]
}

###
GET  http://localhost:3000/api/store/meal/1
Content-Type: application/json
